# Generated by Django 4.2.5 on 2023-11-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='hidden_sentiment',
            field=models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4, verbose_name='Hidden sentiment (not explicitly mentioned but implied)'),
        ),
    ]
